### ISSUE TITLE
More high level description about SaverChef 

### ISSUE THREAD

**Issue by DanielXu222** [CocoLee2/SaverChef#11]
The high level description of SaverChef: "A React Native application with a React Native frontend, Flask backend, and PostgreSQL database" doesn't give us a great description of what SaverChef actually does. A little more description in the ReadMe about what SaverChef does would be awesome!

**Comment by boyulz** [comment]
Hi Daniel! Thanks for reporting the issue. I have updated the README.md file for a better high level description.
